using System;
using System.Linq.Expressions;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Solhigson.Framework.Infrastructure;

namespace Solhigson.Framework.Persistence.Repositories
{
    /*
     * Generated by: Solhigson.Framework.efcoretool
     *
     * https://github.com/solhigson-public/solhigson.framework
     * https://www.nuget.org/packages/solhigson.framework.efcoretool
     *
     * This file is ALWAYS overwritten, DO NOT place custom code here
     */
    public partial class RolePermissionRepository : SolhigsonRepositoryBase<Solhigson.Framework.Persistence.EntityModels.RolePermission
        >, 
            Solhigson.Framework.Persistence.Repositories.Abstractions.IRolePermissionRepository
    {
        public RolePermissionRepository(Solhigson.Framework.Persistence.SolhigsonDbContext dbContext) : base(dbContext)
        {
        }

		public async Task<Solhigson.Framework.Persistence.EntityModels.RolePermission> GetByIdAsync(int id)
		{

			Expression<Func<Solhigson.Framework.Persistence.EntityModels.RolePermission, bool>> query = 
				t => t.Id == id;
			return await GetByCondition(query).FirstOrDefaultAsync();
		}

		public async Task<Solhigson.Framework.Persistence.EntityModels.RolePermission> GetByRoleIdAndPermissionIdAsync(string roleId, string permissionId)
		{
			if (roleId is null || permissionId is null) { return null; }

			Expression<Func<Solhigson.Framework.Persistence.EntityModels.RolePermission, bool>> query = 
				t => t.RoleId == roleId
				&& t.PermissionId == permissionId;
			return await GetByCondition(query).FirstOrDefaultAsync();
		}

		public async Task<System.Collections.Generic.IList<Solhigson.Framework.Persistence.EntityModels.RolePermission>> GetByRoleIdAsync(string roleId)
		{
			if (roleId is null) { return new System.Collections.Generic.List<Solhigson.Framework.Persistence.EntityModels.RolePermission>(); }

			Expression<Func<Solhigson.Framework.Persistence.EntityModels.RolePermission, bool>> query = 
				t => t.RoleId == roleId;
			return await GetByCondition(query).ToListAsync();
		}


    }
}