
namespace Solhigson.Framework.Persistence.Repositories
{
    /*
	 * Generated on: 27-Aug-2021 08:41:47 UTC
     * Generated by: Solhigson.Framework.efcoretool
     *
     * https://github.com/solhigson-public/solhigson.framework
     * https://www.nuget.org/packages/solhigson.framework.efcoretool
     *
     * This file is never overwritten, place custom code here
     */
    public partial class SolhigsonCachedRepositoryBase<T, TCacheModel>
    {
        
    }
}