
namespace Solhigson.Framework.Persistence.Repositories
{
    /*
     * Generated by: Solhigson.Framework.efcoretool
     *
     * https://github.com/solhigson-public/solhigson.framework
     * https://www.nuget.org/packages/solhigson.framework.efcoretool
     *
     * This file is ALWAYS overwritten, DO NOT place custom code here
     */
    public partial class SolhigsonCachedRepositoryBase<T, TCacheModel> 
        : Solhigson.Framework.Data.Repository.CachedRepositoryBase<T, Solhigson.Framework.Persistence.SolhigsonDbContext, TCacheModel> 
        where T : class, new() where TCacheModel : class
    {
        public SolhigsonCachedRepositoryBase(Solhigson.Framework.Persistence.SolhigsonDbContext dbContext) : base(dbContext)
        {
        }
    }
}