
namespace Solhigson.Framework.Persistence.Repositories
{
    /*
     * Generated by: Solhigson.Framework.efcoretool
     *
     * https://github.com/solhigson-public/solhigson.framework
     * https://www.nuget.org/packages/solhigson.framework.efcoretool
     *
     * This file is ALWAYS overwritten, DO NOT place custom code here
     */
    public partial class SolhigsonRepositoryBase<T> : Solhigson.Framework.Data.Repository.RepositoryBase<T, Solhigson.Framework.Persistence.SolhigsonDbContext>, 
        Solhigson.Framework.Persistence.Repositories.Abstractions.ISolhigsonRepositoryBase<T> where T : class, new()
    {
        public SolhigsonRepositoryBase(Solhigson.Framework.Persistence.SolhigsonDbContext dbContext) : base(dbContext)
        {
        }
    }
}