# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - master
  - "*.release"

pool:
  vmImage: 'windows-2022'

variables:
  solution: '**/*.sln'
  frameworkProj: '**/Solhigson.Framework/Solhigson.Framework.csproj'
  toolsProj: '**/Solhigson.Framework.EfCoreTool/Solhigson.Framework.EfCoreTool.csproj'
  azureCosmosProj: '**/Solhigson.Framework.AzureCosmosDb/Solhigson.Framework.AzureCosmosDb.csproj'
  mongoDbProj: '**/Solhigson.Framework.MongoDb/Solhigson.Framework.MongoDb.csproj'
  utilitiesProj: '**/Solhigson.Framework.Utilities/Solhigson.Framework.Utilities.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  isMaster: $[eq(variables['Build.SourceBranchName'], 'master')]
  packageFramework: false
  packageTool: false
  packageAzureCosmosDb: false
  packageMongoDb: true
  packageUtilities: false

stages:
  - stage: build
    condition: and(eq(variables.isMaster, true), eq(variables.packageFramework, false), eq(variables.packageAzureCosmosDb, false), eq(variables.packageTool, false), eq(variables.packageMongoDb, false))
    displayName: Validate Check-in
    jobs:
      - job:
        displayName: Build
        steps:
          - task: NuGetToolInstaller@1
            displayName: Install Nuget Tool

          - task: NuGetCommand@2
            displayName: Restore Nuget Packages
            inputs:
              command: 'restore'
              restoreSolution: '$(solution)'
              feedsToUse: 'config'

          - task: VSBuild@1
            displayName: Build Project
            inputs:
              solution: '$(solution)'
              msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
              platform: '$(buildPlatform)'
              configuration: '$(buildConfiguration)'


  - stage: nuget_package_framework
    condition:  and(eq(variables.isMaster, true), eq(variables.packageFramework, true))
    displayName: Deploy Solhigson Framework package to Nuget.Org
    jobs:
      - job:
        displayName: Package & Push Solhigson Framework
        steps:
          - task: NuGetToolInstaller@1
            displayName: Install Nuget Tool

          - task: NuGetCommand@2
            displayName: Restore Nuget Packages
            inputs:
              command: 'restore'
              restoreSolution: '$(solution)'
              feedsToUse: 'config'

          - task: VSBuild@1
            displayName: Build Project
            inputs:
              solution: '$(solution)'
              msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
              platform: '$(buildPlatform)'
              configuration: '$(buildConfiguration)'

          - task: DotNetCoreCLI@2
            displayName: 'Package Framework'
            inputs:
              command: 'pack'
              packagesToPack: '$(frameworkProj)'
              versioningScheme: 'off'

          - task: NuGetCommand@2
            displayName: 'Push'
            inputs:
              command: 'push'
              packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
              nuGetFeedType: 'external'
              publishFeedCredentials: 'nuget'


  - stage: nuget_package_azureCosmos
    condition:  and(eq(variables.isMaster, true), eq(variables.packageAzureCosmosDb, true))
    displayName: Deploy AzureCosmos Package to Nuget.Org
    jobs:
      - job:
        displayName: Package & Push AzureCosmos Package
        steps:
          - task: NuGetToolInstaller@1
            displayName: Install Nuget Tool

          - task: NuGetCommand@2
            displayName: Restore Nuget Packages
            inputs:
              command: 'restore'
              restoreSolution: '$(solution)'
              feedsToUse: 'config'

          - task: VSBuild@1
            displayName: Build Project
            inputs:
              solution: '$(solution)'
              msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
              platform: '$(buildPlatform)'
              configuration: '$(buildConfiguration)'

          - task: DotNetCoreCLI@2
            displayName: 'Package EfCoreTool'
            inputs:
              command: 'pack'
              packagesToPack: '$(azureCosmosProj)'
              versioningScheme: 'off'

          - task: NuGetCommand@2
            displayName: 'Push'
            inputs:
              command: 'push'
              packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
              nuGetFeedType: 'external'
              publishFeedCredentials: 'nuget'


  - stage: nuget_package_efCoreTool
    condition:  and(eq(variables.isMaster, true), eq(variables.packageTool, true))
    displayName: Deploy EfCoreTool to Nuget.Org
    jobs:
      - job:
        displayName: Package & Push EFCoreTool
        steps:
          - task: NuGetToolInstaller@1
            displayName: Install Nuget Tool

          - task: NuGetCommand@2
            displayName: Restore Nuget Packages
            inputs:
              command: 'restore'
              restoreSolution: '$(solution)'
              feedsToUse: 'config'

          - task: VSBuild@1
            displayName: Build Project
            inputs:
              solution: '$(solution)'
              msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
              platform: '$(buildPlatform)'
              configuration: '$(buildConfiguration)'

          - task: DotNetCoreCLI@2
            displayName: 'Package EfCoreTool'
            inputs:
              command: 'pack'
              packagesToPack: '$(toolsProj)'
              versioningScheme: 'off'

          - task: NuGetCommand@2
            displayName: 'Push'
            inputs:
              command: 'push'
              packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
              nuGetFeedType: 'external'
              publishFeedCredentials: 'nuget'
              
            
            
            


  - stage: nuget_package_mongodb
    condition:  and(eq(variables.isMaster, true), eq(variables.packageMongoDb, true))
    displayName: Deploy Solhigson MongoDb package to Nuget.Org
    jobs:
      - job:
        displayName: Package & Push Solhigson MongoDb
        steps:
          - task: NuGetToolInstaller@1
            displayName: Install Nuget Tool

          - task: NuGetCommand@2
            displayName: Restore Nuget Packages
            inputs:
              command: 'restore'
              restoreSolution: '$(solution)'
              feedsToUse: 'config'

          - task: VSBuild@1
            displayName: Build Project
            inputs:
              solution: '$(solution)'
              msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
              platform: '$(buildPlatform)'
              configuration: '$(buildConfiguration)'

          - task: DotNetCoreCLI@2
            displayName: 'Package MongoDb'
            inputs:
              command: 'pack'
              packagesToPack: '$(mongoDbProj)'
              versioningScheme: 'off'

          - task: NuGetCommand@2
            displayName: 'Push'
            inputs:
              command: 'push'
              packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
              nuGetFeedType: 'external'
              publishFeedCredentials: 'nuget'


  - stage: nuget_package_utilities
    condition:  and(eq(variables.isMaster, true), eq(variables.packageUtilities, true))
    displayName: Deploy Solhigson MongoDb package to Nuget.Org
    jobs:
      - job:
        displayName: Package & Push Solhigson Utilities
        steps:
          - task: NuGetToolInstaller@1
            displayName: Install Nuget Tool

          - task: NuGetCommand@2
            displayName: Restore Nuget Packages
            inputs:
              command: 'restore'
              restoreSolution: '$(solution)'
              feedsToUse: 'config'

          - task: VSBuild@1
            displayName: Build Project
            inputs:
              solution: '$(solution)'
              msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
              platform: '$(buildPlatform)'
              configuration: '$(buildConfiguration)'

          - task: DotNetCoreCLI@2
            displayName: 'Package Utilities'
            inputs:
              command: 'pack'
              packagesToPack: '$(utilitiesProj)'
              versioningScheme: 'off'

          - task: NuGetCommand@2
            displayName: 'Push'
            inputs:
              command: 'push'
              packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
              nuGetFeedType: 'external'
              publishFeedCredentials: 'nuget'
