
namespace Solhigson.Framework.Persistence.CacheModels
{
    /*
	 * Generated on: 28-Aug-2021 11:11:50 UTC
     * Generated by: Solhigson.Framework.efcoretool
     *
     * https://github.com/solhigson-public/solhigson.framework
     * https://www.nuget.org/packages/solhigson.framework.efcoretool
     *
     * This file is never overwritten, place custom code here
     */
    public partial record PermissionCacheModel
    {
        
    }
}