
using Solhigson.Framework.Infrastructure;

namespace Solhigson.Framework.Services
{
    /*
	 * Generated on: 15-Sep-2021 16:17:20 UTC
     * Generated by: Solhigson.Framework.efcoretool
     *
     * https://github.com/solhigson-public/solhigson.framework
     * https://www.nuget.org/packages/solhigson.framework.efcoretool
     *
     * This file is never overwritten, place custom code here
     */
    public abstract partial class ServiceBase
    {
        public SolhigsonServicesWrapper SolhigsonServicesWrapper { get; set; }
    }
}