
namespace Solhigson.Framework.Services
{
    /*
     * Generated by: Solhigson.Framework.efcoretool
     *
     * https://github.com/solhigson-public/solhigson.framework
     * https://www.nuget.org/packages/solhigson.framework.efcoretool
     *
     * This file is ALWAYS overwritten, DO NOT place custom code here
     */
    public abstract partial class ServiceBase : Solhigson.Framework.Services.Abstractions.IServiceBase
    {
        protected Solhigson.Framework.Persistence.Repositories.Abstractions.IRepositoryWrapper RepositoryWrapper { get; }

        public ServiceBase(Solhigson.Framework.Persistence.Repositories.Abstractions.IRepositoryWrapper repositoryWrapper)
        {
            RepositoryWrapper = repositoryWrapper;
        }
    }
}