
namespace Solhigson.Framework.Persistence.Repositories.Abstractions
{
    /*
	 * Generated on: 31-Aug-2021 12:12:37 UTC
     * Generated by: Solhigson.Framework.efcoretool
     *
     * https://github.com/solhigson-public/solhigson.framework
     * https://www.nuget.org/packages/solhigson.framework.efcoretool
     *
     * This file is never overwritten, place custom code here
     */
    public partial interface IAspNetRoleRepository
    {
        
    }
}