using System.Threading.Tasks;

namespace Solhigson.Framework.Persistence.Repositories.Abstractions
{
    /*
     * Generated by: Solhigson.Framework.efcoretool
     *
     * https://github.com/solhigson-public/solhigson.framework
     * https://www.nuget.org/packages/solhigson.framework.efcoretool
     *
     * This file is ALWAYS overwritten, DO NOT place custom code here
     */
    public partial interface IPermissionRepository 
        : Solhigson.Framework.Persistence.Repositories.Abstractions.ISolhigsonCachedRepositoryBase<Solhigson.Framework.Persistence.EntityModels.Permission
            ,Solhigson.Framework.Persistence.CacheModels.PermissionCacheModel>
    {
		Task<Solhigson.Framework.Persistence.EntityModels.Permission> GetByIdAsync(string id);
		Task<Solhigson.Framework.Persistence.EntityModels.Permission> GetByNameAsync(string name);

		//Cached Methods
		Solhigson.Framework.Persistence.CacheModels.PermissionCacheModel GetByIdCached(string id);
		Solhigson.Framework.Persistence.CacheModels.PermissionCacheModel GetByNameCached(string name);
    
    }
}