
namespace Solhigson.Framework.Persistence.Repositories.Abstractions
{
    /*
     * Generated by: Solhigson.Framework.efcoretool
     *
     * https://github.com/solhigson-public/solhigson.framework
     * https://www.nuget.org/packages/solhigson.framework.efcoretool
     *
     * This file is ALWAYS overwritten, DO NOT place custom code here
     */
    public partial interface IRepositoryWrapper
    {
        Solhigson.Framework.Persistence.SolhigsonDbContext DbContext { get; }
        System.Threading.Tasks.Task SaveChangesAsync();
        int SaveChanges();
		Solhigson.Framework.Persistence.Repositories.Abstractions.IAppSettingRepository AppSettingRepository { get; }
		Solhigson.Framework.Persistence.Repositories.Abstractions.IPermissionRepository PermissionRepository { get; }
		Solhigson.Framework.Persistence.Repositories.Abstractions.IRolePermissionRepository RolePermissionRepository { get; }

    }
}