using System.Threading.Tasks;

namespace Solhigson.Framework.Persistence.Repositories.Abstractions
{
    /*
     * Generated by: Solhigson.Framework.efcoretool
     *
     * https://github.com/solhigson-public/solhigson.framework
     * https://www.nuget.org/packages/solhigson.framework.efcoretool
     *
     * This file is ALWAYS overwritten, DO NOT place custom code here
     */
    public partial interface IRolePermissionRepository 
        : Solhigson.Framework.Persistence.Repositories.Abstractions.ISolhigsonRepositoryBase<Solhigson.Framework.Persistence.EntityModels.RolePermission
            >
    {
		Task<Solhigson.Framework.Persistence.EntityModels.RolePermission> GetByIdAsync(int id);
		Task<System.Collections.Generic.IList<Solhigson.Framework.Persistence.EntityModels.RolePermission>> GetByRoleIdAndPermissionIdAsync(string roleId, string permissionId);
    
    }
}