
namespace Solhigson.Framework.Persistence.Repositories.Abstractions
{
    /*
	 * Generated on: 27-Aug-2021 09:07:44 UTC
     * Generated by: Solhigson.Framework.efcoretool
     *
     * https://github.com/solhigson-public/solhigson.framework
     * https://www.nuget.org/packages/solhigson.framework.efcoretool
     *
     * This file is never overwritten, place custom code here
     */
    public partial interface IRolePermissionRepository
    {
        
    }
}