
namespace Solhigson.Framework.Dto
{
    /*
	 * Generated on: 02-Oct-2021 10:42:00 UTC
     * Generated by: Solhigson.Framework.efcoretool
     *
     * https://github.com/solhigson-public/solhigson.framework
     * https://www.nuget.org/packages/solhigson.framework.efcoretool
     *
     * This file is never overwritten, place custom code here
     */
    public partial record AppSettingDto
    {
        
    }
}