
namespace Solhigson.Framework.Dto
{
    /*
	 * Generated on: 27-Aug-2021 08:05:29 UTC
     * Generated by: Solhigson.Framework.efcoretool
     *
     * https://github.com/solhigson-public/solhigson.framework
     * https://www.nuget.org/packages/solhigson.framework.efcoretool
     *
     * This file is never overwritten, place custom code here
     */
    public partial record AppSettingDto
    {
        
    }
}