
namespace Solhigson.Framework.Dto
{
    /*
	 * Generated on: 15-Sep-2021 17:39:02 UTC
     * Generated by: Solhigson.Framework.efcoretool
     *
     * https://github.com/solhigson-public/solhigson.framework
     * https://www.nuget.org/packages/solhigson.framework.efcoretool
     *
     * This file is never overwritten, place custom code here
     */
    public partial record NotificationTemplateDto
    {
        
    }
}