using System;

namespace Solhigson.Framework.Dto
{
    /*
     * Generated by: Solhigson.Framework.efcoretool
     *
     * https://github.com/solhigson-public/solhigson.framework
     * https://www.nuget.org/packages/solhigson.framework.efcoretool
     *
     * This file is ALWAYS overwritten, DO NOT place custom code here
     */
    public partial record PermissionDto
    { 
		public string Id { get; set; }
		public string Name { get; set; }
		public string Description { get; set; }
		public string Url { get; set; }
		public bool IsMenu { get; set; }
		public bool IsMenuRoot { get; set; }
		public string ParentId { get; set; }
		public int MenuIndex { get; set; }
		public string Icon { get; set; }
		public string OnClickFunction { get; set; }
		public bool Enabled { get; set; }

    }
}